import type { CatalogItem, QuoteTemplate } from "./types";

export const seedItems: CatalogItem[] = [
  {
    id: "axis-p3265",
    sku: "AXIS-P3265-LVE",
    name: "Axis P3265-LVE Dome Camera",
    category: "Camera",
    unitPrice: 679,
    msrp: 769,
    vendor: "ADI",
    inventory: 12,
    notes: "Outdoor-ready camera for entry coverage.",
  },
  {
    id: "axis-a8105",
    sku: "AXIS-A8105-E",
    name: "Axis Network Video Door Station",
    category: "Camera",
    unitPrice: 925,
    msrp: 1099,
    vendor: "ADI",
    inventory: 4,
  },
  {
    id: "honeywell-pro4200",
    sku: "PRO4200",
    name: "Honeywell PRO4200 Access Panel",
    category: "Access Control",
    unitPrice: 1185,
    msrp: 1360,
    vendor: "ADI",
    inventory: 7,
  },
  {
    id: "honeywell-reader",
    sku: "OMNI-R10",
    name: "Honeywell Mullion Card Reader",
    category: "Access Control",
    unitPrice: 142,
    msrp: 180,
    vendor: "ADI",
    inventory: 24,
  },
  {
    id: "assa-9600",
    sku: "9600-630",
    name: "ASSA ABLOY 9600 Electric Strike",
    category: "Door Hardware",
    unitPrice: 398,
    msrp: 455,
    vendor: "ADI",
    inventory: 9,
  },
  {
    id: "rex-motion",
    sku: "REX-360",
    name: "Request-to-Exit Motion Sensor",
    category: "Door Hardware",
    unitPrice: 86,
    msrp: 112,
    vendor: "ADI",
    inventory: 16,
  },
  {
    id: "door-contact",
    sku: "DPS-MAG",
    name: "Door Position Switch",
    category: "Door Hardware",
    unitPrice: 38,
    msrp: 55,
    vendor: "ADI",
    inventory: 38,
  },
  {
    id: "poe-switch",
    sku: "POE-8-120W",
    name: "8-Port PoE Network Switch",
    category: "Network",
    unitPrice: 289,
    msrp: 349,
    vendor: "ADI",
    inventory: 11,
  },
  {
    id: "labor-install",
    sku: "LAB-INSTALL",
    name: "Installation Labor",
    category: "Labor",
    unitPrice: 125,
    vendor: "Internal",
    notes: "Hourly labor rate.",
  },
  {
    id: "labor-program",
    sku: "LAB-PROGRAM",
    name: "Programming and Commissioning",
    category: "Labor",
    unitPrice: 145,
    vendor: "Internal",
  },
];

export const seedTemplates: QuoteTemplate[] = [
  {
    id: "one-door",
    name: "One Door Setup",
    description: "Single access-controlled opening with reader, strike, REX, contact, and labor.",
    lines: [
      { itemId: "honeywell-reader", quantity: 1 },
      { itemId: "assa-9600", quantity: 1 },
      { itemId: "rex-motion", quantity: 1 },
      { itemId: "door-contact", quantity: 1 },
      { itemId: "labor-install", quantity: 6 },
      { itemId: "labor-program", quantity: 2 },
    ],
  },
  {
    id: "two-door",
    name: "Two Door Setup",
    description: "Two doors sharing panel hardware with door devices and labor.",
    lines: [
      { itemId: "honeywell-pro4200", quantity: 1 },
      { itemId: "honeywell-reader", quantity: 2 },
      { itemId: "assa-9600", quantity: 2 },
      { itemId: "rex-motion", quantity: 2 },
      { itemId: "door-contact", quantity: 2 },
      { itemId: "labor-install", quantity: 12 },
      { itemId: "labor-program", quantity: 3 },
    ],
  },
  {
    id: "site-starter",
    name: "Whole Site Starter",
    description: "Access panel, cameras, switching, doors, and commissioning for a small site.",
    lines: [
      { itemId: "honeywell-pro4200", quantity: 1 },
      { itemId: "axis-p3265", quantity: 4 },
      { itemId: "poe-switch", quantity: 1 },
      { itemId: "honeywell-reader", quantity: 4 },
      { itemId: "assa-9600", quantity: 4 },
      { itemId: "labor-install", quantity: 28 },
      { itemId: "labor-program", quantity: 6 },
    ],
  },
];
